- hosts: localhost
  become: true
  tasks:
    - name: Install Packages
      apt: name={{item}}
      with_items:
        - zsh
        - zsh-syntax-highlighting
        - vim
        - tmux
        - git
        - wicd-curses
        - xmonad
        - xmobar
        - suckless-tools
        - xscreensaver
        - thunderbird
        - firefox
        - chromium-browser
        - openvpn
        - gnupg2
        - bluetooth
        - silversearcher-ag
    - name: Copy User Files
      copy: src={{ item.src }} dest={{ item.dest }} owner=joseph group=joseph mode=664
      with_items:
        - { src: 'files/dotvimrc', dest: '/home/joseph/.vimrc' }
        - { src: 'files/dottmux.conf', dest: '/home/joseph/.tmux.conf' }
        - { src: 'files/dotzshrc', dest: '/home/joseph/.zshrc' }
        - { src: 'files/dotprofile', dest: '/home/joseph/.profile' }
        - { src: 'files/dotXdefaults', dest: '/home/joseph/.Xdefaults' }
        - { src: 'files/dotxscreensaver', dest: '/home/joseph/.xscreensaver' }
    - name: Use Zsh
      command: usermod --shell /usr/bin/zsh joseph
