- hosts: localhost
  become: true
  tasks:
    - name: Install Packages
      apt: name={{item}}
      with_items:
        - zsh
        - vim
        - tmux
        - git
        - wicd-curses
        - xmonad
        - xmobar
        - suckless-tools
        - xscreensaver
        - thunderbird
        - firefox
        - chromium-browser
        - openvpn
        - gnupg2
        - bluetooth
    - name: Copy User Files
      copy: src={{ item.src }} dest={{ item.dest }} owner=joseph mode=664
      with_items:
        - { src: 'files/dotvimrc', dest: '/home/joseph/.vimrc' }
        - { src: 'files/dottmux.conf', dest: '/home/joseph/.tmux.conf' }
