- hosts: localhost
  become: true
  tasks:
    - name: Install Packages
      apt: name={{item}}
      with_items:
        - zsh
        - zsh-syntax-highlighting
        - vim
        - tmux
        - git
        - wicd-curses
        - xterm
        - xmonad
        - xmobar
        - suckless-tools
        - xscreensaver
        - xinit
        - thunderbird
        - firefox
        - chromium-browser
        - openvpn
        - gnupg2
        - bluetooth
        - silversearcher-ag
        - wget
        - curl
        - laptop-mode-tools
        - upower
        - pass
        - alsa-utils
        - pulseaudio
        - sshuttle
    - name: Ensure User Directories Exist
      file: path={{item}} state=directory owner=joseph group=joseph mode=774
      with_items:
        - /home/joseph/.cache/zsh
        - /home/joseph/.xmonad
        - /home/joseph/go
        - /home/joseph/go/bin
        - /home/joseph/go/pkg
        - /home/joseph/go/src
        - /home/joseph/bin
    - name: Copy User Files
      copy: src={{item.src}} dest={{item.dest}} owner=joseph group=joseph mode=664 force=no
      with_items:
        - { src: 'files/dotvimrc', dest: '/home/joseph/.vimrc' }
        - { src: 'files/dottmux.conf', dest: '/home/joseph/.tmux.conf' }
        - { src: 'files/dotzshrc', dest: '/home/joseph/.zshrc' }
        - { src: 'files/dotprofile', dest: '/home/joseph/.profile' }
        - { src: 'files/dotXdefaults', dest: '/home/joseph/.Xdefaults' }
        - { src: 'files/dotXresources', dest: '/home/joseph/.Xresources' }
        - { src: 'files/dotxinitrc', dest: '/home/joseph/.xinitrc' }
        - { src: 'files/dotxmobarrc', dest: '/home/joseph/.xmobarrc' }
        - { src: 'files/dotxscreensaver', dest: '/home/joseph/.xscreensaver' }
        - { src: 'files/xmonad.hs', dest: '/home/joseph/.xmonad/xmonad.hs' }
    - name: Copy User Scripts
      copy: src={{item.src}} dest={{item.dest}} owner=joseph group=joseph mode=774 force=no
      with_items:
        - { src: 'files/tor-browser', dest: '/home/joseph/bin/tor-browser' }
        - { src: 'files/listppa', dest: '/home/joseph/bin/listppa' }
    - name: Use Zsh
      command: usermod --shell /usr/bin/zsh joseph
    - name: Compile Xmonad
      become: yes
      become_user: joseph
      command: xmonad --recompile
    - name: Install Vundle 
      become: yes
      become_user: joseph
      git: repo=https://github.com/VundleVim/Vundle.vim.git dest=/home/joseph/.vim/bundle/Vundle.vim
    - name: Install Vim Plugins
      become: yes
      become_user: joseph
      shell: vim -E -s -c "source /home/joseph/.vimrc" -c PluginInstall -c qa
      ignore_errors: yes
    - name: Install Snaps
      command: snap install --classic {{item}}
      with_items:
        - skype
#    - name: Install Go
#      shell: |
#        wget -c https://storage.googleapis.com/golang/go1.10.2.linux-amd64.tar.gz
#        tar -C /usr/local -xvzf go1.10.2.linux-amd64.tar.gz
#        rm go1.10.2.linux-amd64.tar.gz
#    - name: Install Tor Browser
#      become: yes
#      become_user: joseph
#      shell: |
#        cd /home/joseph
#        wget -c https://www.torproject.org/dist/torbrowser/7.5.3/tor-browser-linux64-7.5.3_en-US.tar.xz
#        tar -xvJf tor-browser-linux64-7.5.3_en-US.tar.xz
#        rm tor-browser-linux64-7.5.3_en-US.tar.xz



# TODO:
# Add user ssh-agent service.
# Install sublime text.
# Setup YouCompleteMe.
