- hosts: localhost
  become: true
  tasks:
    - name: Install Packages
      apt: name={{item}}
      with_items:
        - zsh
        - vim
        - tmux
        - git
        - wicd-curses
        - xmonad
        - xmobar
        - suckless-tools
        - xscreensaver
        - thunderbird
        - firefox
        - chromium-browser
        - open-vpn
