- hosts: localhost
  become: true
  tasks:
    - name: Install Packages
      apt: name={{item}}
      with_items:
        - zsh
        - zsh-syntax-highlighting
        - vim
        - tmux
        - git
        - wicd-curses
        - xterm
        - xmonad
        - xmobar
        - suckless-tools
        - xscreensaver
        - thunderbird
        - firefox
        - chromium-browser
        - openvpn
        - gnupg2
        - bluetooth
        - silversearcher-ag
        - wget
        - curl
        - laptop-mode-tools
        - upower
    - name: Copy User Files
      copy: src={{ item.src }} dest={{ item.dest }} owner=joseph group=joseph mode=664
      with_items:
        - { src: 'files/dotvimrc', dest: '/home/joseph/.vimrc' }
        - { src: 'files/dottmux.conf', dest: '/home/joseph/.tmux.conf' }
        - { src: 'files/dotzshrc', dest: '/home/joseph/.zshrc' }
        - { src: 'files/dotprofile', dest: '/home/joseph/.profile' }
        - { src: 'files/dotXdefaults', dest: '/home/joseph/.Xdefaults' }
        - { src: 'files/dotxscreensaver', dest: '/home/joseph/.xscreensaver' }
    - name: Use Zsh
      command: usermod --shell /usr/bin/zsh joseph
    - name: Ensure Zsh History Directory Exists
      file: path=/home/joseph/.cache/zsh/dirs state=directory owner=joseph group=joseph mode=664
    - name: Install Vundle 
      become: yes
      become_user: joseph
      git: repo=https://github.com/VundleVim/Vundle.vim.git dest=/home/joseph/.vim/bundle/Vundle.vim
    - name: Install Vim Plugins
      become: yes
      become_user: joseph
      shell: vim +PluginInstall +qall
    - name: Install Snaps
      command: snap install --classic {{item}}
      with_items:
        - skype

# TODO:
# Xmonad config.
# Add user ssh-agent service.
# Install sublime text.
# Install Go.
# Install Tor browser.
